## REST Client 확장 프로그램 사용
## 외부 연동 테스트
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

### 로그인
POST http://{{host}}/api/user/login HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "wallet_id" : "123123123123"
}

### 나의 보유 NFT
POST http://{{host}}/api/mypage/getMyItemList HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "wallet_id" : "0xf53783026ff5B8bb35a685F48bc9cC7536d8652D",
    "page" : 1
}

### 나의 보유 NFT 등록
POST http://{{host}}/api/mypage/setMyItemListing HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "wallet_id" : "0xf53783026ff5B8bb35a685F48bc9cC7536d8652D",
    "nft_token_id" : 3,
    "nft_price" : 1000,
    "nft_duration_date" : 1664352329
}